### ISSUE TITLE
Add Robotium

### ISSUE THREAD

**Issue by jverbraeken** [ericcornelissen/NervousFish#101]
- Parent issues: -
- Relevant issues: -
- Estimated effort: 3

* * *

## User story
As a developer I want to be able to make in little time a nice integration test so that I save time compared to using Cucumber.

## What
This issue demands the addition of Robotium to the project.

## Why
This issue is needed for the project because Robotium makes it possible to develop integration tests in quite less time than when using Cucumber.

## How
This feature can be added by implementing Robotium.

## Definition of done
This task can be considered done when

- Robotium is implemented
- At least one example is provided to prove that Robotium is working

**Comment by clenrock** [comment]
We will not use this anymore, partly because this program is paid and we got a solution already.
