### ISSUE TITLE
New contact activity

### ISSUE THREAD

**Issue by jverbraeken** [ericcornelissen/NervousFish#120]
- Parent issues: #104
- Relevant issues: #69 
- Estimated effort: 8 hrs (Joost)

* * *

## User story
As a user I want to be able to add new contacts after I received them so that I can add some extra information about them.

## What
This issue demands to let the user enter some information about new contacts.

## Why
This issue is needed for the project because the user wants the public keys to be assigned to contacts.

## How
This feature can be added by adding a new contact activity that allows the user to enter, inter alia, a name, a phone number, an email address and a home address

## Definition of done
This task can be considered done when

- The user can specify some user-dependent details about a new user
- The details are saved along with the new user in the database

**Comment by clenrock** [comment]
Done with PR #130
