### ISSUE TITLE
Generate Personal Keys

### ISSUE THREAD

**Issue by KilianCallebaut** [ericcornelissen/NervousFish#154]

**Comment by KilianCallebaut** [comment]
User story
As a product owner I want to generate a public and a private key on first use or when I ask to regenerate them.

What
This issue demands that there is a public and private key generated without having to regenerate one on every usage.

Why
This issue is needed because we need something to exchange, have a unique object in database for saving the personal keys and generate a key by the user's wishes.

How
This feature can be added by adding a method that generates the keys on first usage of the app, which also can be called by a button.

Definition of done
This task can be considered done when the app generates a public and private key on first usage or by pressing a button and storing them in the database so they can be uniquely found as the user's own keys.

Notes

**Comment by clenrock** [comment]
A bit longer explained in #162
