### ISSUE TITLE
No servicelocator when restarting after crash

### ISSUE THREAD

**Issue by clenrock** [ericcornelissen/NervousFish#182]
- Parent issues: -
- Relevant issues: -

* * *

## Description of the bug
When the app crashes and you press restart the app, the app will restart on the activity where it crashed. The problem here is that when it restarts at another place than the EntryActivity, the servicelocator is not created. So the app crashes again because the servicelocator is null.

## Possible solution
Maybe check if a message or event is shown that there was a restart, because this should go to the EntryActivity.

**Comment by clenrock** [comment]
Maybe a fix would be to have a check in every onStart method of an Activity which checks if ServiceLocator is null. If that is true, then go to the EntryActivity.
(Could be that there is a nicer fix possible)

**Comment by ericcornelissen** [comment]
> Maybe a fix would be to have a check in every onStart method of an Activity which checks if ServiceLocator is null. If that is true, then go to the EntryActivity.

That would be a nice hotfix imo, we can look at other solutions later 😄
