### ISSUE TITLE
[ON HOLD] Enable Bluetooth when MainActivity is opened

### ISSUE THREAD

**Issue by jverbraeken** [ericcornelissen/NervousFish#198]
- Parent issues: -
- Relevant issues: -
- Estimated effort: -

* * *

## User story
As a user I want to have my device listen for incoming pairing requests immediately after logging in so that I do not have to the bluetooth pairing initiating screen first

## What
This issue demands to enable Bluetooth on devices with Bluetooth in MainActivity, possibly by showing a notification (on first use) to ask the user if he wants that and if he wants to remember that choice

## Why
This issue is needed for the project because it's not intuitive to having to go to the screen to initiate a Bluetooth connection to accept a Bluetooth pairing request from somebody else

## How
This feature can be added by enabling Bluetooth on devices with Bluetooth in MainActivity, possibly by showing a notification (on first use) to ask the user if he wants that and if he wants to remember that choice

## Definition of ready
This features is not ready until the following issues are finished:

- #195 

## Definition of done
This task can be considered done when

- Bluetooth is enabled on devices with Bluetooth in MainActivity
- A notification is shown (on first use) to ask the user if he wants to listen on Bluetooth for pairing requests in the main screen already
- The notification asks the user if he wants to remember that choice

**Comment by ericcornelissen** [comment]
Are you aware this part of develop, and it is even being improved upon in #194 ?

**Comment by jverbraeken** [comment]
@ericcornelissen I am fully aware that that is part of develop, but in #195 that's not the case anymore. It's too risky to fix that just before the demo, but next week I want it in MainActivity again. I'm not quite sure if #194 works with #195, we'll see...

**Comment by ericcornelissen** [comment]
How should these two influence each other? I would say #195 didn't/barely changed anything in the `MainActivity` related to the changes in #194.


> It's too risky to fix that just before the demo...

Is not really a reason why this PR is needed, putting that PR [ON HOLD] (as you already did) is a more appropriate solution I would say...

**Comment by clenrock** [comment]
This is already implemented right? PR #194 only improved upon this.

**Comment by ericcornelissen** [comment]
Yes, and from the looks of [it](https://github.com/ericcornelissen/NervousFish/blob/80624afad8478220fdd3223b57dc7cc3d4c09e40/app/src/main/java/com/nervousfish/nervousfish/activities/MainActivity.java#L105) it is also still part of #195
