### ISSUE TITLE
Improve testing of RhythmActivity

### ISSUE THREAD

**Issue by clenrock** [ericcornelissen/NervousFish#220]
- Parent issues: - #195
- Relevant issues: -
- Estimated effort: - 5 hours (estimated by Cornel)

* * *

## User story
As a developer I want to be sure that the code used for the secure layer of the Bluetooth pairing works correctly so that I can build on top of it and be sure it will not break when a user uses it.

## What
This issue demands that there are unit, and integration tests created for classes like the RhythmActivity and the WaitActivity. Also the classes that can be tested should be excluded from cobertura.

## Why
This issue is needed for the project because this code works how we want to, but we would like to have unit tests to automatically check that it works fine in the future.

## How
This feature can be added by creating integration tests and unit tests.

## Definition of ready
This features is not ready until the following issues are finished:

- #195 is merged

## Definition of done
This task can be considered done when

- [x] As much as possible is tested in the classes used in Bluetooth pairing.
- [x] Classes that can't be tested are excluded in the Jacoco report.

**Comment by ericcornelissen** [comment]
This has been added a while ago, see [RhythmCreateActivitySteps.java](https://github.com/ericcornelissen/NervousFish/blob/develop/app/src/androidTest/java/com/nervousfish/nervousfish/test/RhythmCreateActivitySteps.java)
