### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by jverbraeken** [ericcornelissen/NervousFish#27]
[//]: # "Check if the title is descriptive!"
- Parent issues: #1
- Relevant issues: #10, #11, #12, #14
- Estimated effort: 4 hours

* * *

## User story
As a developer I want to have a database in which the data of the user is stored

## What
We want to have a database in which user data is stored. The user data can be split up into two fraction: the user data (public/private key pair+name) and contact data (public keys+name of other people).

## Why
The data of the user is there so it can be used by other application and so the public key+name can be exchanged with others.

The data of the contacts is needed so the user can send encrypted messages to them using their public key. The name is needed so the user can identify them.

## How
There will be a database package that will be used to perform the action described above so the application can actually store data into/read from the database.

The actual database will be implemented in JSON files because it is easy and good enough (at least for now) since the data/queries are not complex and it is only needed locally.

## Definition of done
This task is done once it is possible to perform certain tasks with regards to the database:
- [x] Create a new contact in the database (i.e. an entry with public key and name).
- [x] Modify a contact in the database (i.e. change the name).
- [x] Delete a contact from the database (i.e. remove the entry, key+name, completely).
- [x] Get a list of all contacts from the database (i.e. a list of the names of all contacts).
- [x] ~~Get a specific contact from the database (i.e. all information about that contact, name+key).~~
- [x] Get your own details from the database (i.e. all information about you, name+key).
- [x] Create your info, public and private key+name, in the database.
- [x] Update your name in the database.

## Notes
n/a

**Comment by ericcornelissen** [comment]
> Get a specific contact from the database (i.e. all information about that contact, name+key).

I propose we remove this bullet, as it is not relevant to our implementation. First and foremost because once we request the list of all contact, we already have all information about each contact so we don't need to request more information. Also, this would require some kind of identifier (requesting a contact using the `Contact` class would be a little silly) which we don't really need...

What do you think @clenrock?

**Comment by clenrock** [comment]
@ericcornelissen I agree! We got everything in an array already

**Comment by ericcornelissen** [comment]
I updated the description 👍
