### ISSUE TITLE
Product vision

### ISSUE THREAD

**Issue by jverbraeken** [ericcornelissen/NervousFish#31]
Subtask of #33 

As a product owner I want to have a product vision so that I have a clear understanding of the project

**Comment by ericcornelissen** [comment]
The first draft of our Product Vision can be found here @MrHug: [Product vision Nervous fish (1st draft).pdf](https://github.com/ericcornelissen/NervousFish/files/976865/Product.vision_Nervous.fish_1st.draft.pdf)

**Comment by ericcornelissen** [comment]
@jverbraeken Why did you close this issue? We're not yet done with this, we have to hand in the final version next week...
