### ISSUE TITLE
Product planning

### ISSUE THREAD

**Issue by jverbraeken** [ericcornelissen/NervousFish#33]
As a product owner I want:
- [x] an analysis of the context, problem, and stakeholder inputs. The analysis is complete and should clearly define the steps needed to complete the project (#31)
- [x] a prioritization of all backlog that's reasonable and well motivated.
- [x] well documented user stories that fully capture the 'who', 'what', 'why' of the requirement and a sufficient motivation 
- [x]  to have a road-map containing the major release schedule and goals and that depicts fully the overall plan and connections among parts

**Comment by ericcornelissen** [comment]
Some additional context about the documents that need to be delivered:

> ... The Product Vision aims to show *what* you are going to build and *why*. The product planning explains how you *plan* to build the product (high level) and the Architecture Design Document is really for developers to explain *how* it is build exactly.

**Comment by ericcornelissen** [comment]
The first draft of our Product Planning can be found here @foresterre: [Product planning Nervous fish (1st draft).pdf](https://github.com/ericcornelissen/NervousFish/files/976884/Product.planning_Nervous.fish_1st.draft.pdf)

**Comment by ericcornelissen** [comment]
We're not yet done with this, we have to hand in the final version next week 😉

**Comment by ericcornelissen** [comment]
@jverbraeken, why do you keep closing this? We're not yet done with this, we have to hand in the final version next week...
