### ISSUE TITLE
Connecting devices flowchart

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/NervousFish#51]
[//]: # "Check if the title is descriptive!"
- Parent issues: #30
- Relevant issues: #53

* * *

Flow chart for starting a connection (Bluetooth or NFC):
![connection flowchart](http://i.imgur.com/2dZxudM.jpg)

Any suggestions/remarks on missing or unclear steps?

* * *

##### Previous versions
[4 may 2017](http://i.imgur.com/CiJFf3y.jpg)
[5 may 2017](http://i.imgur.com/Bu8YN6h.jpg)

**Comment by TheBonheurs** [comment]
When is modify triggered while verifying (and what is it exactly)? I understood that as changing the values saved in the app's database on a device, which are things like contact name etc. and such action would be possible after one successful verification, so either after the confirmation via the main activity or another edit activity or something. This could also be done without any connection (offline) by one of the users after once being successfully verified and exchanging information.

**Comment by ericcornelissen** [comment]
> When is modify triggered while verifying (and what is it exactly)?

It is indeed changing the value saved in the app's database on the device! But it seems the chart is not all that clear 🤔 My idea was to show the user a confirmation screen (verify in the chart, but I think confirmation is clearer for what I intent to say) on which there are three different actions: confirm the contact, reject the contact or (immediately) modify the contact. This last action would prevent the user from having the perform three steps to modify the new contact (first confirming the contact, then finding & selecting the contact, then modifying the contact).

**Comment by TheBonheurs** [comment]
Ah I get it now 💡 . I think with the explanation you gave beneath the chart it should become clear to anyone who is reading it, irrespective of the name 👍

**Comment by ericcornelissen** [comment]
@jverbraeken why did you close this issue?
