### ISSUE TITLE
Contact management flowchart

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/NervousFish#53]
[//]: # "Check if the title is descriptive!"
- Parent issues: #30
- Relevant issues: #51

* * *

Flow chart for editing/removing an existing contact:
![contact flowchart](http://i.imgur.com/SRGDDru.jpg)

Any suggestions/remarks on missing or unclear steps?

**Comment by jverbraeken** [comment]
Could you add a third action, namely show public key (which we will probably implement by showing a QR code)

**Comment by ericcornelissen** [comment]
> Could you add a third action, namely show public key

I would say the public key is included in the "Contact details", what is your opinion on this?


> which we will probably implement by showing a QR code

What do you mean? Why would we display it as a QR code?

**Comment by ericcornelissen** [comment]
@jverbraeken, why did you close this PR? It was not done to begin with. But even worse, the discussion wasn't finished yet...
