### ISSUE TITLE
NFC key exchange

### ISSUE THREAD

**Issue by jverbraeken** [ericcornelissen/NervousFish#8]
- Parent issues: -
- Relevant issues: -
- Estimated effort: -

* * *

## User story
As a user I want to receive a public key of a person by using NFC so that I can receive their public key easily and safely.

## What
This issue demands a way to exchange a public key by using NFC

## Why
This issue is needed for the project because it's easy and safe to use NFC to get somebody's public key

## How
This feature can be added by providing a way to beam the public key over NFC to other devices and by providing a way to receive this public key and using it to create a new contact

## Definition of done
This task can be considered done when

- There is a button to start beaming the user's QR code
- There is a button to listen for incoming public keys over NFC
- The public key is extracted from the NFC data
- The user can add a new contact with this public key
- The changes are reflected in the database

**Comment by ericcornelissen** [comment]
In `develop` since #231
